source 'https://rubygems.org'

gem 'activesupport'
gem 'awesome_print'
gem 'faker'
gem 'guard'
gem 'guard-minitest'
gem 'hashie'
gem "minitest"
gem 'minitest-power_assert'
gem 'minitest-reporters'
gem 'nokogiri'
gem 'oga'
gem 'pry'
gem 'recursive-open-struct'
